// Liste CURATÉE d'entrée du catalogue MiMai (modèles de chat GGUF pour téléphones Android).
//
// Ce fichier ne contient AUCUNE valeur technique (taille, sha256, contexte, licence...) :
// tout cela est lu/vérifié en ligne par scripts/build-catalog.mjs. Ici on ne met que des
// choix éditoriaux : quel dépôt, quelles quantifications, nom lisible, étiquettes, explication.
//
// Champs d'une entrée :
//   slug     identifiant de base (kebab-case) ; id final = `${slug}-${quant en minuscules}`
//   repo     dépôt Hugging Face (non protégé, vérifié sans authentification)
//   family   famille affichée
//   name     nom lisible
//   quants   liste de quantifications ("Q4_K_M", "Q8_0"...) ; le fichier est retrouvé par nom
//   files    (optionnel) { QUANT: "fichier.gguf" } quand le nom ne suit pas la convention
//   ids      (optionnel) { QUANT: "id-historique" } : ids déjà stockés chez les utilisateurs
//   tags     parmi francais, multilingue, code, raisonnement, leger, equilibre, precis,
//            long-contexte, maths (les tags leger/equilibre/precis/long-contexte sont aussi
//            ajoutés automatiquement d'après la taille / le contexte vérifiés)
//   explain  1 phrase FR honnête, sans chiffre de benchmark
//   score    estimation éditoriale 0-100 de la qualité attendue en chat sur téléphone
//            (sert uniquement au classement "rank", voir build-catalog.mjs)
//   legacy   true : reprend à l'identique les valeurs de la graine (3 ids historiques)

export const CURATED = [
  // ───────────────────────── Qwen ─────────────────────────
  { slug: 'qwen3-8b', repo: 'unsloth/Qwen3-8B-GGUF', family: 'Qwen', name: 'Qwen 3 8B', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'raisonnement', 'precis'], score: 93,
    explain: 'Très capable en réflexion et en multilingue, mais lourd : réservé aux téléphones de 8 Go et plus.' },
  { slug: 'qwen3.5-4b', repo: 'unsloth/Qwen3.5-4B-GGUF', family: 'Qwen', name: 'Qwen 3.5 4B', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['francais', 'multilingue', 'raisonnement', 'long-contexte'], score: 91,
    explain: 'Génération récente de Qwen en 4 milliards de paramètres : très bon compromis qualité/taille sur téléphone récent.' },
  { slug: 'qwen3.5-2b', repo: 'unsloth/Qwen3.5-2B-GGUF', family: 'Qwen', name: 'Qwen 3.5 2B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 80,
    explain: 'Petit modèle récent de la famille Qwen 3.5, rapide et multilingue.' },
  { slug: 'qwen3.5-0.8b', repo: 'unsloth/Qwen3.5-0.8B-GGUF', family: 'Qwen', name: 'Qwen 3.5 0.8B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'leger'], score: 62,
    explain: 'Très léger et récent : convient aux téléphones modestes pour des réponses courtes.' },
  { slug: 'qwen3-4b-instruct-2507', repo: 'unsloth/Qwen3-4B-Instruct-2507-GGUF', family: 'Qwen', name: 'Qwen 3 4B Instruct 2507', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['francais', 'multilingue', 'long-contexte', 'precis'], score: 90,
    explain: 'Version Instruct (sans mode réflexion) de Qwen 3 4B : réponses directes et rapides, bon niveau général.' },
  { slug: 'qwen3-4b-thinking-2507', repo: 'unsloth/Qwen3-4B-Thinking-2507-GGUF', family: 'Qwen', name: 'Qwen 3 4B Thinking 2507', quants: ['Q4_K_M'],
    tags: ['multilingue', 'raisonnement', 'maths', 'long-contexte'], score: 88,
    explain: 'Modèle de raisonnement : rédige une longue réflexion avant de répondre, utile pour la logique et les maths mais plus lent.' },
  { slug: 'qwen3-4b', repo: 'Qwen/Qwen3-4B-GGUF', family: 'Qwen', name: 'Qwen 3 4B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'raisonnement'], score: 87,
    explain: 'Modèle officiel Qwen 3 4B, avec mode réflexion optionnel ; bonne polyvalence.' },
  { slug: 'qwen3-1.7b', repo: 'unsloth/Qwen3-1.7B-GGUF', family: 'Qwen', name: 'Qwen 3 1.7B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'raisonnement'], score: 70,
    explain: 'Petit modèle Qwen 3 : rapide, correct pour des questions simples.' },
  { slug: 'qwen3-0.6b', repo: 'unsloth/Qwen3-0.6B-GGUF', family: 'Qwen', name: 'Qwen 3 0.6B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'leger'], score: 52,
    explain: 'Minuscule et très rapide ; qualité limitée, à réserver aux appareils très modestes.' },
  { slug: 'qwen2.5-7b', repo: 'bartowski/Qwen2.5-7B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 7B Instruct', quants: ['Q4_K_M', 'IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis', 'long-contexte'], score: 85,
    explain: 'Modèle 7B éprouvé, très bon en français et en code léger ; demande un téléphone de 8 Go.' },
  { slug: 'qwen2.5-3b', repo: 'Qwen/Qwen2.5-3B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 3B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue'], score: 72,
    explain: 'Bon équilibre pour les téléphones de 6 Go, nettement plus précis que les modèles de 1,5 B.' },
  { slug: 'qwen2.5-1.5b', repo: 'Qwen/Qwen2.5-1.5B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 1.5B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    ids: { Q4_K_M: 'qwen15b' }, legacy: ['Q4_K_M'],
    tags: ['francais', 'precis'], score: 58,
    explain: 'Plus précis, pour les téléphones avec 6 Go de mémoire ou plus.' },
  { slug: 'qwen2.5-0.5b', repo: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 0.5B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    ids: { Q4_K_M: 'qwen05b' }, legacy: ['Q4_K_M'],
    tags: ['francais', 'leger'], score: 42,
    explain: 'Le plus rapide et le plus léger : idéal pour démarrer sur tout téléphone.' },
  { slug: 'qwen2.5-coder-7b', repo: 'Qwen/Qwen2.5-Coder-7B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 Coder 7B Instruct', quants: ['Q4_K_M'],
    tags: ['code', 'precis'], score: 78,
    explain: 'Spécialisé dans la programmation (génération, correction, explication de code) ; 8 Go de mémoire recommandés.' },
  { slug: 'qwen2.5-coder-3b', repo: 'Qwen/Qwen2.5-Coder-3B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 Coder 3B Instruct', quants: ['Q4_K_M'],
    tags: ['code'], score: 68,
    explain: 'Assistant de programmation compact pour téléphones de 6 Go.' },
  { slug: 'qwen2.5-coder-1.5b', repo: 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 Coder 1.5B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['code'], score: 56,
    explain: 'Petit assistant de code rapide, pour des extraits courts.' },
  { slug: 'qwen2.5-coder-0.5b', repo: 'Qwen/Qwen2.5-Coder-0.5B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 Coder 0.5B Instruct', quants: ['Q4_K_M'],
    tags: ['code', 'leger'], score: 40,
    explain: 'Le plus petit modèle orienté code : très rapide mais limité.' },
  { slug: 'qwen2.5-math-1.5b', repo: 'bartowski/Qwen2.5-Math-1.5B-Instruct-GGUF', family: 'Qwen', name: 'Qwen 2.5 Math 1.5B Instruct', quants: ['Q4_K_M'],
    tags: ['maths', 'raisonnement'], score: 50,
    explain: 'Spécialisé dans les problèmes de mathématiques ; peu adapté à la conversation générale.' },

  // ───────────────────────── Gemma ─────────────────────────
  { slug: 'gemma4-e4b', repo: 'unsloth/gemma-4-E4B-it-GGUF', family: 'Gemma', name: 'Gemma 4 E4B', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis', 'long-contexte'], score: 90,
    explain: 'Gemma 4 « E4B » (4 B effectifs) : très bonne qualité ; le nombre de paramètres affiché inclut des embeddings, d\'où un fichier plus gros que le nom ne le suggère.' },
  { slug: 'gemma4-e2b', repo: 'unsloth/gemma-4-E2B-it-GGUF', family: 'Gemma', name: 'Gemma 4 E2B', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 84,
    explain: 'Gemma 4 « E2B » (2 B effectifs) : conçu pour le mobile, bon niveau multilingue ; le nombre de paramètres affiché inclut des embeddings.' },
  { slug: 'gemma3n-e4b', repo: 'unsloth/gemma-3n-E4B-it-GGUF', family: 'Gemma', name: 'Gemma 3n E4B', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue', 'precis'], score: 88,
    explain: 'Gemma 3n « E4B » (4 B effectifs) pensé pour les appareils mobiles ; texte uniquement ici ; le nombre de paramètres affiché inclut des embeddings.' },
  { slug: 'gemma3n-e2b', repo: 'unsloth/gemma-3n-E2B-it-GGUF', family: 'Gemma', name: 'Gemma 3n E2B', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue'], score: 80,
    explain: 'Gemma 3n « E2B » (2 B effectifs) pensé pour les appareils mobiles ; texte uniquement ici ; le nombre de paramètres affiché inclut des embeddings.' },
  { slug: 'gemma3-4b', repo: 'unsloth/gemma-3-4b-it-GGUF', family: 'Gemma', name: 'Gemma 3 4B Instruct', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 84,
    explain: 'Très bon en français et dans de nombreuses langues ; texte uniquement ici (la vision n\'est pas utilisée).' },
  { slug: 'gemma3-1b', repo: 'unsloth/gemma-3-1b-it-GGUF', family: 'Gemma', name: 'Gemma 3 1B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'leger'], score: 64,
    explain: 'Petit Gemma 3 : rapide et multilingue, bon pour les téléphones d\'entrée de gamme.' },
  { slug: 'gemma3-270m', repo: 'unsloth/gemma-3-270m-it-GGUF', family: 'Gemma', name: 'Gemma 3 270M Instruct', quants: ['Q8_0'],
    tags: ['leger'], score: 30,
    explain: 'Modèle ultra-compact, plutôt fait pour être spécialisé ; réponses générales très limitées.' },
  { slug: 'gemma2-2b', repo: 'bartowski/gemma-2-2b-it-GGUF', family: 'Gemma', name: 'Gemma 2 2B Instruct', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['equilibre'], score: 66,
    explain: 'Gemma 2 en 2 B : réponses soignées en anglais, correct en français, contexte court.' },

  // ───────────────────────── Llama ─────────────────────────
  { slug: 'llama3.1-8b', repo: 'bartowski/Meta-Llama-3.1-8B-Instruct-GGUF', family: 'Llama', name: 'Llama 3.1 8B Instruct', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis', 'long-contexte'], score: 82,
    explain: 'Référence 8 B de Meta ; quantification IQ4_XS pour tenir sur 8 Go de mémoire (un peu plus lente que Q4_K_M).' },
  { slug: 'llama3.2-3b', repo: 'bartowski/Llama-3.2-3B-Instruct-GGUF', family: 'Llama', name: 'Llama 3.2 3B Instruct', quants: ['Q4_K_M', 'Q5_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 74,
    explain: 'Modèle de Meta pour appareils mobiles, bon en français et en suivi de consignes.' },
  { slug: 'llama3.2-1b', repo: 'bartowski/Llama-3.2-1B-Instruct-GGUF', family: 'Llama', name: 'Llama 3.2 1B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'leger', 'long-contexte'], score: 60,
    explain: 'Petit modèle de Meta, rapide, avec un long contexte.' },
  { slug: 'hermes3-llama3.2-3b', repo: 'bartowski/Hermes-3-Llama-3.2-3B-GGUF', family: 'Llama', name: 'Hermes 3 (Llama 3.2) 3B', quants: ['Q4_K_M'],
    tags: ['multilingue'], score: 70,
    explain: 'Variante Llama 3.2 3B affinée par Nous Research pour le dialogue et le suivi de consignes.' },
  { slug: 'nemotron-nano-4b', repo: 'bartowski/nvidia_Llama-3.1-Nemotron-Nano-4B-v1.1-GGUF', family: 'Llama', name: 'Llama 3.1 Nemotron Nano 4B', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'maths', 'code'], score: 78,
    explain: 'Modèle de raisonnement de NVIDIA (dérivé de Llama 3.1) : réfléchit avant de répondre, surtout utile en maths et en code.' },
  { slug: 'nemotron-mini-4b', repo: 'bartowski/Nemotron-Mini-4B-Instruct-GGUF', family: 'Nemotron', name: 'Nemotron Mini 4B Instruct', quants: ['Q4_K_M'],
    tags: [], score: 64,
    explain: 'Petit modèle de NVIDIA orienté dialogue et jeux de rôle, essentiellement en anglais.' },
  { slug: 'deepseek-r1-distill-llama-8b', repo: 'unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF', family: 'DeepSeek', name: 'DeepSeek R1 Distill Llama 8B', quants: ['IQ4_XS'],
    tags: ['raisonnement', 'maths'], score: 74,
    explain: 'Raisonnement distillé de DeepSeek R1 dans une base Llama ; longue réflexion avant la réponse, 8 Go de mémoire requis.' },

  // ───────────────────────── Phi ─────────────────────────
  { slug: 'phi4-mini', repo: 'unsloth/Phi-4-mini-instruct-GGUF', family: 'Phi', name: 'Phi 4 Mini Instruct', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['multilingue', 'raisonnement', 'code', 'maths', 'long-contexte'], score: 80,
    explain: 'Petit modèle de Microsoft entraîné sur des données de raisonnement : solide en logique, maths et code.' },
  { slug: 'phi4-mini-reasoning', repo: 'unsloth/Phi-4-mini-reasoning-GGUF', family: 'Phi', name: 'Phi 4 Mini Reasoning', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'maths'], score: 72,
    explain: 'Spécialisé dans le raisonnement mathématique pas à pas ; pas fait pour la conversation courante.' },
  { slug: 'phi3.5-mini', repo: 'bartowski/Phi-3.5-mini-instruct-GGUF', family: 'Phi', name: 'Phi 3.5 Mini Instruct', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['multilingue', 'raisonnement', 'long-contexte'], score: 72,
    explain: 'Modèle compact de Microsoft au long contexte, fort en logique ; français correct sans plus.' },
  { slug: 'phi3-mini-4k', repo: 'microsoft/Phi-3-mini-4k-instruct-gguf', family: 'Phi', name: 'Phi 3 Mini 4K Instruct', quants: [],
    files: { Q4_K_M: 'Phi-3-mini-4k-instruct-q4.gguf' }, tags: ['raisonnement'], score: 64,
    explain: 'Première génération de Phi 3 Mini (contexte court de 4K), surtout utile en anglais.' },

  // ───────────────────────── SmolLM ─────────────────────────
  { slug: 'smollm3-3b', repo: 'ggml-org/SmolLM3-3B-GGUF', family: 'SmolLM', name: 'SmolLM3 3B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'raisonnement', 'long-contexte'], score: 80,
    explain: 'Modèle ouvert de Hugging Face avec mode réflexion et long contexte ; multilingue (dont le français).' },
  { slug: 'smollm2-1.7b', repo: 'HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF', family: 'SmolLM', name: 'SmolLM2 1.7B Instruct', quants: ['Q4_K_M'],
    ids: { Q4_K_M: 'smollm17b' }, legacy: ['Q4_K_M'],
    tags: ['equilibre'], score: 60,
    explain: 'Un bon équilibre entre qualité de réponse et vitesse sur appareil récent.' },
  { slug: 'smollm2-360m', repo: 'HuggingFaceTB/SmolLM2-360M-Instruct-GGUF', family: 'SmolLM', name: 'SmolLM2 360M Instruct', quants: ['Q8_0'],
    tags: ['leger'], score: 36,
    explain: 'Très petit modèle anglophone de Hugging Face, pour des tâches simples.' },

  // ───────────────────────── Mistral ─────────────────────────
  { slug: 'ministral3-8b', repo: 'unsloth/Ministral-3-8B-Instruct-2512-GGUF', family: 'Mistral', name: 'Ministral 3 8B Instruct 2512', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis', 'long-contexte'], score: 88,
    explain: 'Modèle 8 B de Mistral AI, très bon en français ; quantification IQ4_XS pour tenir sur 8 Go.' },
  { slug: 'ministral3-3b', repo: 'unsloth/Ministral-3-3B-Instruct-2512-GGUF', family: 'Mistral', name: 'Ministral 3 3B Instruct 2512', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 82,
    explain: 'Petit modèle de Mistral AI (français natif), texte uniquement ici.' },
  { slug: 'ministral-8b-2410', repo: 'bartowski/Ministral-8B-Instruct-2410-GGUF', family: 'Mistral', name: 'Ministral 8B Instruct 2410', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis', 'long-contexte'], score: 76,
    explain: 'Modèle 8 B de Mistral AI (octobre 2024) ; licence de recherche, usage non commercial.' },
  { slug: 'mistral-7b-v0.3', repo: 'bartowski/Mistral-7B-Instruct-v0.3-GGUF', family: 'Mistral', name: 'Mistral 7B Instruct v0.3', quants: ['Q4_K_M', 'IQ4_XS'],
    tags: ['francais', 'precis'], score: 70,
    explain: 'Classique 7 B de Mistral AI, à l\'aise en français ; plus ancien que les modèles récents mais robuste.' },

  // ───────────────────────── DeepSeek ─────────────────────────
  { slug: 'deepseek-r1-0528-qwen3-8b', repo: 'unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF', family: 'DeepSeek', name: 'DeepSeek R1 0528 Qwen3 8B', quants: ['IQ4_XS'],
    tags: ['raisonnement', 'maths', 'code'], score: 88,
    explain: 'Raisonnement distillé de DeepSeek R1 dans une base Qwen 3 8B : très fort en logique mais lent et gourmand (8 Go).' },
  { slug: 'deepseek-r1-distill-qwen-7b', repo: 'bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF', family: 'DeepSeek', name: 'DeepSeek R1 Distill Qwen 7B', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'maths'], score: 72,
    explain: 'Modèle de raisonnement : écrit sa réflexion avant de répondre, plus lent ; 8 Go de mémoire recommandés.' },
  { slug: 'deepseek-r1-distill-qwen-1.5b', repo: 'bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF', family: 'DeepSeek', name: 'DeepSeek R1 Distill Qwen 1.5B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['raisonnement', 'maths'], score: 55,
    explain: 'Petit modèle de raisonnement : montre sa réflexion, utile pour des problèmes simples de logique et de maths.' },

  // ───────────────────────── Granite (IBM) ─────────────────────────
  { slug: 'granite4.1-3b', repo: 'ibm-granite/granite-4.1-3b-GGUF', family: 'Granite', name: 'Granite 4.1 3B', quants: ['Q4_K_M', 'Q5_K_M'],
    tags: ['multilingue', 'francais', 'code'], score: 78,
    explain: 'Modèle d\'entreprise d\'IBM, bon pour le suivi de consignes et l\'appel d\'outils.' },
  { slug: 'granite4.0-micro', repo: 'ibm-granite/granite-4.0-micro-GGUF', family: 'Granite', name: 'Granite 4.0 Micro (3B)', quants: ['Q4_K_M'],
    tags: ['multilingue', 'francais', 'code'], score: 74,
    explain: 'Granite 4.0 en version dense 3 B, licence Apache.' },
  { slug: 'granite4.0-h-tiny', repo: 'ibm-granite/granite-4.0-h-tiny-GGUF', family: 'Granite', name: 'Granite 4.0 H Tiny (7B MoE)', quants: ['Q4_K_M'],
    tags: ['multilingue', 'francais', 'long-contexte'], score: 76,
    explain: 'Architecture hybride Mamba et experts (7 B au total, ~1 B actifs par mot) : rapide pour sa taille, mais fichier de plus de 4 Go.' },
  { slug: 'granite4.0-h-micro', repo: 'ibm-granite/granite-4.0-h-micro-GGUF', family: 'Granite', name: 'Granite 4.0 H Micro (3B)', quants: ['Q4_K_M'],
    tags: ['multilingue', 'francais', 'long-contexte'], score: 72,
    explain: 'Version hybride Mamba de Granite 4.0 : économe en mémoire sur les longs contextes.' },
  { slug: 'granite4.0-1b', repo: 'ibm-granite/granite-4.0-1b-GGUF', family: 'Granite', name: 'Granite 4.0 1B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'francais'], score: 58,
    explain: 'Petit modèle d\'IBM sous licence Apache, rapide.' },
  { slug: 'granite4.0-h-1b', repo: 'ibm-granite/granite-4.0-h-1b-GGUF', family: 'Granite', name: 'Granite 4.0 H 1B', quants: ['Q4_K_M'],
    tags: ['multilingue', 'long-contexte'], score: 56,
    explain: 'Version hybride Mamba, 1 B : très légère, bien adaptée aux longs contextes.' },
  { slug: 'granite4.0-h-350m', repo: 'ibm-granite/granite-4.0-h-350m-GGUF', family: 'Granite', name: 'Granite 4.0 H 350M', quants: ['Q8_0'],
    tags: ['leger'], score: 34,
    explain: 'Modèle minuscule d\'IBM pour tâches simples (extraction, classification).' },
  { slug: 'granite3.3-2b', repo: 'ibm-granite/granite-3.3-2b-instruct-GGUF', family: 'Granite', name: 'Granite 3.3 2B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'francais'], score: 62,
    explain: 'Modèle 2 B d\'IBM, correct en français, sous licence Apache.' },

  // ───────────────────────── Falcon (TII) ─────────────────────────
  { slug: 'falcon3-7b', repo: 'tiiuae/Falcon3-7B-Instruct-GGUF', family: 'Falcon', name: 'Falcon3 7B Instruct', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue', 'maths', 'code'], score: 70,
    explain: 'Modèle 7 B du TII (Émirats), correct en maths, code et français ; 8 Go recommandés.' },
  { slug: 'falcon3-3b', repo: 'tiiuae/Falcon3-3B-Instruct-GGUF', family: 'Falcon', name: 'Falcon3 3B Instruct', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue'], score: 64,
    explain: 'Falcon3 3 B : bon rapport taille/qualité pour les téléphones de 6 Go.' },
  { slug: 'falcon3-1b', repo: 'tiiuae/Falcon3-1B-Instruct-GGUF', family: 'Falcon', name: 'Falcon3 1B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['francais', 'multilingue'], score: 52,
    explain: 'Petit Falcon3, rapide.' },
  { slug: 'falcon-h1-3b', repo: 'tiiuae/Falcon-H1-3B-Instruct-GGUF', family: 'Falcon', name: 'Falcon-H1 3B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'long-contexte'], score: 74,
    explain: 'Architecture hybride (attention + Mamba) du TII : contexte long à moindre coût mémoire.' },
  { slug: 'falcon-h1-1.5b', repo: 'tiiuae/Falcon-H1-1.5B-Instruct-GGUF', family: 'Falcon', name: 'Falcon-H1 1.5B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'long-contexte'], score: 63,
    explain: 'Falcon-H1 hybride en 1,5 B : léger et bon contexte long.' },
  { slug: 'falcon-h1-0.5b', repo: 'tiiuae/Falcon-H1-0.5B-Instruct-GGUF', family: 'Falcon', name: 'Falcon-H1 0.5B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'leger'], score: 44,
    explain: 'Très petit modèle hybride, pour appareils modestes.' },

  // ───────────────────────── Liquid AI ─────────────────────────
  { slug: 'lfm2.5-2.6b', repo: 'LiquidAI/LFM2.5-2.6B-GGUF', family: 'LFM', name: 'LFM 2.5 2.6B', quants: ['Q4_K_M'],
    tags: ['multilingue', 'equilibre'], score: 77,
    explain: 'Modèle de Liquid AI conçu pour tourner vite sur appareil ; multilingue.' },
  { slug: 'lfm2.5-1.2b-instruct', repo: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF', family: 'LFM', name: 'LFM 2.5 1.2B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'leger'], score: 66,
    explain: 'Petit modèle de Liquid AI très rapide sur processeur mobile.' },
  { slug: 'lfm2.5-1.2b-thinking', repo: 'LiquidAI/LFM2.5-1.2B-Thinking-GGUF', family: 'LFM', name: 'LFM 2.5 1.2B Thinking', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'multilingue', 'leger'], score: 64,
    explain: 'Variante à mode réflexion du LFM 2.5 1.2B : plus lente à répondre mais plus méthodique.' },
  { slug: 'lfm2.5-350m', repo: 'LiquidAI/LFM2.5-350M-GGUF', family: 'LFM', name: 'LFM 2.5 350M', quants: ['Q8_0'],
    tags: ['leger'], score: 38,
    explain: 'Minuscule modèle de Liquid AI pour tâches très simples.' },
  { slug: 'lfm2-2.6b', repo: 'LiquidAI/LFM2-2.6B-GGUF', family: 'LFM', name: 'LFM 2 2.6B', quants: ['Q4_K_M'],
    tags: ['multilingue', 'equilibre'], score: 72,
    explain: 'Génération précédente de Liquid AI en 2,6 B, rapide sur mobile.' },
  { slug: 'lfm2-1.2b', repo: 'LiquidAI/LFM2-1.2B-GGUF', family: 'LFM', name: 'LFM 2 1.2B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue', 'leger'], score: 58,
    explain: 'Petit modèle de Liquid AI, très rapide sur téléphone.' },
  { slug: 'lfm2-700m', repo: 'LiquidAI/LFM2-700M-GGUF', family: 'LFM', name: 'LFM 2 700M', quants: ['Q4_K_M'],
    tags: ['multilingue', 'leger'], score: 46,
    explain: 'Modèle très léger de Liquid AI.' },
  { slug: 'lfm2-350m', repo: 'LiquidAI/LFM2-350M-GGUF', family: 'LFM', name: 'LFM 2 350M', quants: ['Q8_0'],
    tags: ['leger'], score: 34,
    explain: 'Le plus petit LFM 2, pour tâches très simples.' },

  // ───────────────────────── Autres familles ─────────────────────────
  { slug: 'olmo3-7b-instruct', repo: 'unsloth/Olmo-3-7B-Instruct-GGUF', family: 'OLMo', name: 'OLMo 3 7B Instruct', quants: ['Q4_K_M'],
    tags: ['precis'], score: 80,
    explain: 'Modèle 100 % ouvert (données et code) de l\'Allen Institute, surtout anglophone ; 8 Go recommandés.' },
  { slug: 'olmo3-7b-think', repo: 'unsloth/Olmo-3-7B-Think-GGUF', family: 'OLMo', name: 'OLMo 3 7B Think', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'maths'], score: 77,
    explain: 'Version raisonnement d\'OLMo 3 : longue réflexion avant la réponse, surtout anglophone.' },
  { slug: 'olmo2-7b', repo: 'bartowski/OLMo-2-1124-7B-Instruct-GGUF', family: 'OLMo', name: 'OLMo 2 7B Instruct', quants: ['Q4_K_M'],
    tags: [], score: 66,
    explain: 'Modèle 100 % ouvert de l\'Allen Institute (2024), surtout anglophone.' },
  { slug: 'olmo2-1b', repo: 'allenai/OLMo-2-0425-1B-Instruct-GGUF', family: 'OLMo', name: 'OLMo 2 1B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: [], score: 48,
    explain: 'Petit modèle 100 % ouvert de l\'Allen Institute, surtout anglophone.' },
  { slug: 'jan-v1-4b', repo: 'janhq/Jan-v1-4B-GGUF', family: 'Qwen', name: 'Jan v1 4B', quants: ['Q4_K_M'],
    tags: ['raisonnement', 'multilingue'], score: 85,
    explain: 'Dérivé de Qwen 3 4B affiné par Jan pour la recherche et l\'utilisation d\'outils.' },
  { slug: 'nanbeige4.2-3b', repo: 'bartowski/Nanbeige_Nanbeige4.2-3B-GGUF', family: 'Nanbeige', name: 'Nanbeige 4.2 3B', quants: ['Q4_K_M'],
    tags: ['raisonnement'], score: 82,
    explain: 'Modèle récent 3 B orienté raisonnement, surtout fort en anglais et en chinois.' },
  { slug: 'apertus-8b', repo: 'unsloth/Apertus-8B-Instruct-2509-GGUF', family: 'Apertus', name: 'Apertus 8B Instruct 2509', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'long-contexte'], score: 78,
    explain: 'Modèle ouvert suisse entraîné sur plus de 1 000 langues (français, allemand, italien...) ; 8 Go requis.' },
  { slug: 'hunyuan-7b', repo: 'bartowski/tencent_Hunyuan-7B-Instruct-GGUF', family: 'Hunyuan', name: 'Hunyuan 7B Instruct', quants: ['Q4_K_M'],
    tags: ['multilingue', 'long-contexte'], score: 74,
    explain: 'Modèle 7 B de Tencent, très fort en chinois ; 8 Go recommandés.' },
  { slug: 'hunyuan-4b', repo: 'bartowski/tencent_Hunyuan-4B-Instruct-GGUF', family: 'Hunyuan', name: 'Hunyuan 4B Instruct', quants: ['Q4_K_M'],
    tags: ['multilingue', 'long-contexte'], score: 70,
    explain: 'Modèle 4 B de Tencent avec très long contexte ; plutôt orienté chinois et anglais.' },
  { slug: 'hunyuan-1.8b', repo: 'bartowski/tencent_Hunyuan-1.8B-Instruct-GGUF', family: 'Hunyuan', name: 'Hunyuan 1.8B Instruct', quants: ['Q4_K_M'],
    tags: ['multilingue', 'long-contexte'], score: 56,
    explain: 'Petit modèle de Tencent à long contexte ; plutôt orienté chinois et anglais.' },
  { slug: 'hunyuan-0.5b', repo: 'bartowski/tencent_Hunyuan-0.5B-Instruct-GGUF', family: 'Hunyuan', name: 'Hunyuan 0.5B Instruct', quants: ['Q4_K_M'],
    tags: ['multilingue', 'leger'], score: 40,
    explain: 'Très petit modèle de Tencent à long contexte.' },
  { slug: 'exaone4-1.2b', repo: 'LGAI-EXAONE/EXAONE-4.0-1.2B-GGUF', family: 'EXAONE', name: 'EXAONE 4.0 1.2B', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['raisonnement', 'multilingue'], score: 62,
    explain: 'Petit modèle de LG AI Research (coréen, anglais, espagnol) ; licence non commerciale.' },
  { slug: 'exaone3.5-7.8b', repo: 'LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct-GGUF', family: 'EXAONE', name: 'EXAONE 3.5 7.8B Instruct', quants: ['Q4_K_M'],
    tags: ['precis', 'long-contexte'], score: 74,
    explain: 'Modèle 7,8 B de LG AI Research, fort en anglais et coréen ; licence non commerciale.' },
  { slug: 'exaone3.5-2.4b', repo: 'LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct-GGUF', family: 'EXAONE', name: 'EXAONE 3.5 2.4B Instruct', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['long-contexte'], score: 64,
    explain: 'Modèle 2,4 B de LG AI Research, fort en anglais et coréen ; licence non commerciale.' },
  { slug: 'internlm2.5-7b', repo: 'internlm/internlm2_5-7b-chat-gguf', family: 'InternLM', name: 'InternLM 2.5 7B Chat', quants: ['Q4_K_M'],
    tags: ['long-contexte', 'maths'], score: 68,
    explain: 'Modèle 7 B du Shanghai AI Lab, bon en raisonnement et très long contexte ; 8 Go recommandés.' },
  { slug: 'internlm2.5-1.8b', repo: 'internlm/internlm2_5-1_8b-chat-gguf', family: 'InternLM', name: 'InternLM 2.5 1.8B Chat', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['long-contexte'], score: 52,
    explain: 'Petit modèle du Shanghai AI Lab, surtout fort en chinois et en anglais.' },
  { slug: 'yi1.5-6b', repo: 'bartowski/Yi-1.5-6B-Chat-GGUF', family: 'Yi', name: 'Yi 1.5 6B Chat', quants: ['Q4_K_M'],
    tags: ['multilingue'], score: 62,
    explain: 'Modèle 6 B de 01.AI, bilingue chinois/anglais ; contexte limité à 4K.' },
  { slug: 'glm-edge-4b', repo: 'THUDM/glm-edge-4b-chat-gguf', family: 'GLM', name: 'GLM-Edge 4B Chat', quants: ['Q4_K_M'],
    tags: ['multilingue'], score: 58,
    explain: 'Modèle de Zhipu AI conçu pour les appareils embarqués, surtout chinois et anglais.' },
  { slug: 'glm-edge-1.5b', repo: 'THUDM/glm-edge-1.5b-chat-gguf', family: 'GLM', name: 'GLM-Edge 1.5B Chat', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['multilingue'], score: 46,
    explain: 'Petit modèle de Zhipu AI pour appareils embarqués, surtout chinois et anglais.' },
  { slug: 'aya-expanse-8b', repo: 'bartowski/aya-expanse-8b-GGUF', family: 'Aya', name: 'Aya Expanse 8B', quants: ['IQ4_XS'],
    tags: ['francais', 'multilingue', 'precis'], score: 70,
    explain: 'Modèle multilingue de Cohere For AI (23 langues dont le français) ; licence non commerciale, 8 Go requis.' },
  { slug: 'eurollm-1.7b', repo: 'mradermacher/EuroLLM-1.7B-Instruct-GGUF', family: 'EuroLLM', name: 'EuroLLM 1.7B Instruct', quants: ['Q4_K_M'],
    tags: ['francais', 'multilingue'], score: 54,
    explain: 'Modèle européen entraîné sur toutes les langues officielles de l\'UE, dont le français.' },
  { slug: 'smallthinker-4b-a0.6b', repo: 'Tiiny/SmallThinker-4BA0.6B-Instruct-GGUF', family: 'SmallThinker', name: 'SmallThinker 4B-A0.6B Instruct', quants: ['Q4_0'],
    tags: ['raisonnement'], score: 62,
    explain: 'Modèle à experts (4 B au total, 0,6 B actifs) conçu pour être rapide sur appareil local ; surtout anglophone.' },
  { slug: 'ernie4.5-0.3b', repo: 'unsloth/ERNIE-4.5-0.3B-PT-GGUF', family: 'ERNIE', name: 'ERNIE 4.5 0.3B', quants: ['Q8_0'],
    tags: ['leger'], score: 34,
    explain: 'Modèle minuscule de Baidu, plutôt chinois et anglais.' },
  { slug: 'tinyllama-1.1b', repo: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF', family: 'TinyLlama', name: 'TinyLlama 1.1B Chat', quants: ['Q4_K_M', 'Q8_0'],
    tags: ['leger'], score: 30,
    explain: 'Petit modèle ancien (2023), anglophone, utile surtout pour tester.' },
  { slug: 'stablelm2-zephyr-1.6b', repo: 'stabilityai/stablelm-2-zephyr-1_6b', family: 'StableLM', name: 'StableLM 2 Zephyr 1.6B', quants: ['Q5_K_M'],
    tags: ['multilingue'], score: 40,
    explain: 'Petit modèle de Stability AI (anglais, français, allemand, espagnol...), assez ancien.' },
];

// Graine historique (ids déjà stockés chez les utilisateurs) : valeurs figées, ne JAMAIS les modifier.
export const LEGACY = [
  {
    "id": "qwen05b",
    "name": "Qwen 2.5 0.5B Instruct",
    "family": "Qwen",
    "paramsB": 0.5,
    "paramsLabel": "0,5 B",
    "quant": "Q4_K_M",
    "ctx": "32K",
    "license": "Apache-2.0",
    "tags": [
      "francais",
      "leger"
    ],
    "explain": "Le plus rapide et le plus léger : idéal pour démarrer sur tout téléphone.",
    "sizeBytes": 491400032,
    "sha256": "74a4da8c9fdbcd15bd1f6d01d621410d31c6fc00986f5eb687824e7b93d7a9db",
    "file": "qwen2.5-0.5b-instruct-q4_k_m.gguf",
    "url": "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
    "repo": "Qwen/Qwen2.5-0.5B-Instruct-GGUF",
    "needRamGb": 1.3
  },
  {
    "id": "smollm17b",
    "name": "SmolLM2 1.7B Instruct",
    "family": "SmolLM",
    "paramsB": 1.7,
    "paramsLabel": "1,7 B",
    "quant": "Q4_K_M",
    "ctx": "8K",
    "license": "Apache-2.0",
    "tags": [
      "equilibre"
    ],
    "explain": "Un bon équilibre entre qualité de réponse et vitesse sur appareil récent.",
    "sizeBytes": 1055609536,
    "sha256": "decd2598bc2c8ed08c19adc3c8fdd461ee19ed5708679d1c54ef54a5a30d4f33",
    "file": "smollm2-1.7b-instruct-q4_k_m.gguf",
    "url": "https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf",
    "repo": "HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF",
    "needRamGb": 1.9
  },
  {
    "id": "qwen15b",
    "name": "Qwen 2.5 1.5B Instruct",
    "family": "Qwen",
    "paramsB": 1.5,
    "paramsLabel": "1,5 B",
    "quant": "Q4_K_M",
    "ctx": "32K",
    "license": "Apache-2.0",
    "tags": [
      "francais",
      "precis"
    ],
    "explain": "Plus précis, pour les téléphones avec 6 Go de mémoire ou plus.",
    "sizeBytes": 1117320736,
    "sha256": "6a1a2eb6d15622bf3c96857206351ba97e1af16c30d7a74ee38970e434e9407e",
    "file": "qwen2.5-1.5b-instruct-q4_k_m.gguf",
    "url": "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf",
    "repo": "Qwen/Qwen2.5-1.5B-Instruct-GGUF",
    "needRamGb": 2
  }
];
